 characters = [
  {
    c_name: "Luke Skywalker",
    height: "172",
    mass: "77",
    hair_color: "blond",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "19BBY",
    gender: "male",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "C-3PO",
    height: "167",
    mass: "75",
    hair_color: "NA",
    skin_color: "gold",
    eye_color: "yellow",
    birth_year: "112BBY",
    gender: "NA",
    homeworld: "Tatooine",
    species: "Droid"
  },
  {
    c_name: "R2-D2",
    height: "96",
    mass: "32",
    hair_color: "NA",
    skin_color: "white, blue",
    eye_color: "red",
    birth_year: "33BBY",
    gender: "NA",
    homeworld: "Naboo",
    species: "Droid"
  },
  {
    c_name: "Darth Vader",
    height: "202",
    mass: "136",
    hair_color: "none",
    skin_color: "white",
    eye_color: "yellow",
    birth_year: "41.9BBY",
    gender: "male",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "Leia Organa",
    height: "150",
    mass: "49",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "19BBY",
    gender: "female",
    homeworld: "Alderaan",
    species: "Human"
  },
  {
    c_name: "Owen Lars",
    height: "178",
    mass: "120",
    hair_color: "brown, grey",
    skin_color: "light",
    eye_color: "blue",
    birth_year: "52BBY",
    gender: "male",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "Beru Whitesun lars",
    height: "165",
    mass: "75",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "blue",
    birth_year: "47BBY",
    gender: "female",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "R5-D4",
    height: "97",
    mass: "32",
    hair_color: "NA",
    skin_color: "white, red",
    eye_color: "red",
    birth_year: "NA",
    gender: "NA",
    homeworld: "Tatooine",
    species: "Droid"
  },
  {
    c_name: "Biggs Darklighter",
    height: "183",
    mass: "84",
    hair_color: "black",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "24BBY",
    gender: "male",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "Obi-Wan Kenobi",
    height: "182",
    mass: "77",
    hair_color: "auburn, white",
    skin_color: "fair",
    eye_color: "blue-gray",
    birth_year: "57BBY",
    gender: "male",
    homeworld: "Stewjon",
    species: "Human"
  },
  {
    c_name: "Anakin Skywalker",
    height: "188",
    mass: "84",
    hair_color: "blond",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "41.9BBY",
    gender: "male",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "Wilhuff Tarkin",
    height: "180",
    mass: "",
    hair_color: "auburn, grey",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "64BBY",
    gender: "male",
    homeworld: "Eriadu",
    species: "Human"
  },
  {
    c_name: "Chewbacca",
    height: "228",
    mass: "112",
    hair_color: "brown",
    skin_color: "NA",
    eye_color: "blue",
    birth_year: "200BBY",
    gender: "male",
    homeworld: "Kashyyyk",
    species: "Wookiee"
  },
  {
    c_name: "Han Solo",
    height: "180",
    mass: "80",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "29BBY",
    gender: "male",
    homeworld: "Corellia",
    species: "Human"
  },
  {
    c_name: "Greedo",
    height: "173",
    mass: "74",
    hair_color: "NA",
    skin_color: "green",
    eye_color: "black",
    birth_year: "44BBY",
    gender: "male",
    homeworld: "Rodia",
    species: "Rodian"
  },
  {
    c_name: "Jabba Desilijic Tiure",
    height: "175",
    mass: "1358",
    hair_color: "NA",
    skin_color: "green-tan, brown",
    eye_color: "orange",
    birth_year: "600BBY",
    gender: "hermaphrodite",
    homeworld: "Nal Hutta",
    species: "Hutt"
  },
  {
    c_name: "Wedge Antilles",
    height: "170",
    mass: "77",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "hazel",
    birth_year: "21BBY",
    gender: "male",
    homeworld: "Corellia",
    species: "Human"
  },
  {
    c_name: "Jek Tono Porkins",
    height: "180",
    mass: "110",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "NA",
    gender: "male",
    homeworld: "Bestine IV",
    species: "Human"
  },
  {
    c_name: "Yoda",
    height: "66",
    mass: "17",
    hair_color: "white",
    skin_color: "green",
    eye_color: "brown",
    birth_year: "896BBY",
    gender: "male",
    homeworld: "NA",
    species: "Yoda's species"
  },
  {
    c_name: "Palpatine",
    height: "170",
    mass: "75",
    hair_color: "grey",
    skin_color: "pale",
    eye_color: "yellow",
    birth_year: "82BBY",
    gender: "male",
    homeworld: "Naboo",
    species: "Human"
  },
  {
    c_name: "Boba Fett",
    height: "183",
    mass: "78.2",
    hair_color: "black",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "31.5BBY",
    gender: "male",
    homeworld: "Kamino",
    species: "Human"
  },
  {
    c_name: "IG-88",
    height: "200",
    mass: "140",
    hair_color: "none",
    skin_color: "metal",
    eye_color: "red",
    birth_year: "15BBY",
    gender: "none",
    homeworld: "NA",
    species: "Droid"
  },
  {
    c_name: "Bossk",
    height: "190",
    mass: "113",
    hair_color: "none",
    skin_color: "green",
    eye_color: "red",
    birth_year: "53BBY",
    gender: "male",
    homeworld: "Trandosha",
    species: "Trandoshan"
  },
  {
    c_name: "Lando Calrissian",
    height: "177",
    mass: "79",
    hair_color: "black",
    skin_color: "dark",
    eye_color: "brown",
    birth_year: "31BBY",
    gender: "male",
    homeworld: "Socorro",
    species: "Human"
  },
  {
    c_name: "Lobot",
    height: "175",
    mass: "79",
    hair_color: "none",
    skin_color: "light",
    eye_color: "blue",
    birth_year: "37BBY",
    gender: "male",
    homeworld: "Bespin",
    species: "Human"
  },
  {
    c_name: "Ackbar",
    height: "180",
    mass: "83",
    hair_color: "none",
    skin_color: "brown mottle",
    eye_color: "orange",
    birth_year: "41BBY",
    gender: "male",
    homeworld: "Mon Cala",
    species: "Mon Calamari"
  },
  {
    c_name: "Mon Mothma",
    height: "150",
    mass: "",
    hair_color: "auburn",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "48BBY",
    gender: "female",
    homeworld: "Chandrila",
    species: "Human"
  },
  {
    c_name: "Arvel Crynyd",
    height: "",
    mass: "",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "NA",
    gender: "male",
    homeworld: "NA",
    species: "Human"
  },
  {
    c_name: "Wicket Systri Warrick",
    height: "88",
    mass: "20",
    hair_color: "brown",
    skin_color: "brown",
    eye_color: "brown",
    birth_year: "8BBY",
    gender: "male",
    homeworld: "Endor",
    species: "Ewok"
  },
  {
    c_name: "Nien Nunb",
    height: "160",
    mass: "68",
    hair_color: "none",
    skin_color: "grey",
    eye_color: "black",
    birth_year: "NA",
    gender: "male",
    homeworld: "Sullust",
    species: "Sullustan"
  },
  {
    c_name: "Qui-Gon Jinn",
    height: "193",
    mass: "89",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "92BBY",
    gender: "male",
    homeworld: "NA",
    species: "Human"
  },
  {
    c_name: "Nute Gunray",
    height: "191",
    mass: "90",
    hair_color: "none",
    skin_color: "mottled green",
    eye_color: "red",
    birth_year: "NA",
    gender: "male",
    homeworld: "Cato Neimoidia",
    species: "Neimodian"
  },
  {
    c_name: "Finis Valorum",
    height: "170",
    mass: "",
    hair_color: "blond",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "91BBY",
    gender: "male",
    homeworld: "Coruscant",
    species: "Human"
  },
  {
    c_name: "Jar Jar Binks",
    height: "196",
    mass: "66",
    hair_color: "none",
    skin_color: "orange",
    eye_color: "orange",
    birth_year: "52BBY",
    gender: "male",
    homeworld: "Naboo",
    species: "Gungan"
  },
  {
    c_name: "Roos Tarpals",
    height: "224",
    mass: "82",
    hair_color: "none",
    skin_color: "grey",
    eye_color: "orange",
    birth_year: "NA",
    gender: "male",
    homeworld: "Naboo",
    species: "Gungan"
  },
  {
    c_name: "Rugor Nass",
    height: "206",
    mass: "",
    hair_color: "none",
    skin_color: "green",
    eye_color: "orange",
    birth_year: "NA",
    gender: "male",
    homeworld: "Naboo",
    species: "Gungan"
  },
  {
    c_name: "Ric Olié",
    height: "183",
    mass: "",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "NA",
    gender: "male",
    homeworld: "Naboo",
    species: "NA"
  },
  {
    c_name: "Watto",
    height: "137",
    mass: "",
    hair_color: "black",
    skin_color: "blue, grey",
    eye_color: "yellow",
    birth_year: "NA",
    gender: "male",
    homeworld: "Toydaria",
    species: "Toydarian"
  },
  {
    c_name: "Sebulba",
    height: "112",
    mass: "40",
    hair_color: "none",
    skin_color: "grey, red",
    eye_color: "orange",
    birth_year: "NA",
    gender: "male",
    homeworld: "Malastare",
    species: "Dug"
  },
  {
    c_name: "Quarsh Panaka",
    height: "183",
    mass: "",
    hair_color: "black",
    skin_color: "dark",
    eye_color: "brown",
    birth_year: "62BBY",
    gender: "male",
    homeworld: "Naboo",
    species: "NA"
  },
  {
    c_name: "Shmi Skywalker",
    height: "163",
    mass: "",
    hair_color: "black",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "72BBY",
    gender: "female",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "Darth Maul",
    height: "175",
    mass: "80",
    hair_color: "none",
    skin_color: "red",
    eye_color: "yellow",
    birth_year: "54BBY",
    gender: "male",
    homeworld: "Dathomir",
    species: "Zabrak"
  },
  {
    c_name: "Bib Fortuna",
    height: "180",
    mass: "",
    hair_color: "none",
    skin_color: "pale",
    eye_color: "pink",
    birth_year: "NA",
    gender: "male",
    homeworld: "Ryloth",
    species: "Twi'lek"
  },
  {
    c_name: "Ayla Secura",
    height: "178",
    mass: "55",
    hair_color: "none",
    skin_color: "blue",
    eye_color: "hazel",
    birth_year: "48BBY",
    gender: "female",
    homeworld: "Ryloth",
    species: "Twi'lek"
  },
  {
    c_name: "Dud Bolt",
    height: "94",
    mass: "45",
    hair_color: "none",
    skin_color: "blue, grey",
    eye_color: "yellow",
    birth_year: "NA",
    gender: "male",
    homeworld: "Vulpter",
    species: "Vulptereen"
  },
  {
    c_name: "Gasgano",
    height: "122",
    mass: "",
    hair_color: "none",
    skin_color: "white, blue",
    eye_color: "black",
    birth_year: "NA",
    gender: "male",
    homeworld: "Troiken",
    species: "Xexto"
  },
  {
    c_name: "Ben Quadinaros",
    height: "163",
    mass: "65",
    hair_color: "none",
    skin_color: "grey, green, yellow",
    eye_color: "orange",
    birth_year: "NA",
    gender: "male",
    homeworld: "Tund",
    species: "Toong"
  },
  {
    c_name: "Mace Windu",
    height: "188",
    mass: "84",
    hair_color: "none",
    skin_color: "dark",
    eye_color: "brown",
    birth_year: "72BBY",
    gender: "male",
    homeworld: "Haruun Kal",
    species: "Human"
  },
  {
    c_name: "Ki-Adi-Mundi",
    height: "198",
    mass: "82",
    hair_color: "white",
    skin_color: "pale",
    eye_color: "yellow",
    birth_year: "92BBY",
    gender: "male",
    homeworld: "Cerea",
    species: "Cerean"
  },
  {
    c_name: "Kit Fisto",
    height: "196",
    mass: "87",
    hair_color: "none",
    skin_color: "green",
    eye_color: "black",
    birth_year: "NA",
    gender: "male",
    homeworld: "Glee Anselm",
    species: "Nautolan"
  },
  {
    c_name: "Eeth Koth",
    height: "171",
    mass: "",
    hair_color: "black",
    skin_color: "brown",
    eye_color: "brown",
    birth_year: "NA",
    gender: "male",
    homeworld: "Iridonia",
    species: "Zabrak"
  },
  {
    c_name: "Adi Gallia",
    height: "184",
    mass: "50",
    hair_color: "none",
    skin_color: "dark",
    eye_color: "blue",
    birth_year: "NA",
    gender: "female",
    homeworld: "Coruscant",
    species: "Tholothian"
  },
  {
    c_name: "Saesee Tiin",
    height: "188",
    mass: "",
    hair_color: "none",
    skin_color: "pale",
    eye_color: "orange",
    birth_year: "NA",
    gender: "male",
    homeworld: "Iktotch",
    species: "Iktotchi"
  },
  {
    c_name: "Yarael Poof",
    height: "264",
    mass: "",
    hair_color: "none",
    skin_color: "white",
    eye_color: "yellow",
    birth_year: "NA",
    gender: "male",
    homeworld: "Quermia",
    species: "Quermian"
  },
  {
    c_name: "Plo Koon",
    height: "188",
    mass: "80",
    hair_color: "none",
    skin_color: "orange",
    eye_color: "black",
    birth_year: "22BBY",
    gender: "male",
    homeworld: "Dorin",
    species: "Kel Dor"
  },
  {
    c_name: "Mas Amedda",
    height: "196",
    mass: "",
    hair_color: "none",
    skin_color: "blue",
    eye_color: "blue",
    birth_year: "NA",
    gender: "male",
    homeworld: "Champala",
    species: "Chagrian"
  },
  {
    c_name: "Gregar Typho",
    height: "185",
    mass: "85",
    hair_color: "black",
    skin_color: "dark",
    eye_color: "brown",
    birth_year: "NA",
    gender: "male",
    homeworld: "Naboo",
    species: "Human"
  },
  {
    c_name: "Cordé",
    height: "157",
    mass: "",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "NA",
    gender: "female",
    homeworld: "Naboo",
    species: "Human"
  },
  {
    c_name: "Cliegg Lars",
    height: "183",
    mass: "",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "82BBY",
    gender: "male",
    homeworld: "Tatooine",
    species: "Human"
  },
  {
    c_name: "Poggle the Lesser",
    height: "183",
    mass: "80",
    hair_color: "none",
    skin_color: "green",
    eye_color: "yellow",
    birth_year: "NA",
    gender: "male",
    homeworld: "Geonosis",
    species: "Geonosian"
  },
  {
    c_name: "Luminara Unduli",
    height: "170",
    mass: "56.2",
    hair_color: "black",
    skin_color: "yellow",
    eye_color: "blue",
    birth_year: "58BBY",
    gender: "female",
    homeworld: "Mirial",
    species: "Mirialan"
  },
  {
    c_name: "Barriss Offee",
    height: "166",
    mass: "50",
    hair_color: "black",
    skin_color: "yellow",
    eye_color: "blue",
    birth_year: "40BBY",
    gender: "female",
    homeworld: "Mirial",
    species: "Mirialan"
  },
  {
    c_name: "Dormé",
    height: "165",
    mass: "",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "NA",
    gender: "female",
    homeworld: "Naboo",
    species: "Human"
  },
  {
    c_name: "Dooku",
    height: "193",
    mass: "80",
    hair_color: "white",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "102BBY",
    gender: "male",
    homeworld: "Serenno",
    species: "Human"
  },
  {
    c_name: "Bail Prestor Organa",
    height: "191",
    mass: "",
    hair_color: "black",
    skin_color: "tan",
    eye_color: "brown",
    birth_year: "67BBY",
    gender: "male",
    homeworld: "Alderaan",
    species: "Human"
  },
  {
    c_name: "Jango Fett",
    height: "183",
    mass: "79",
    hair_color: "black",
    skin_color: "tan",
    eye_color: "brown",
    birth_year: "66BBY",
    gender: "male",
    homeworld: "Concord Dawn",
    species: "Human"
  },
  {
    c_name: "Zam Wesell",
    height: "168",
    mass: "55",
    hair_color: "blonde",
    skin_color: "fair, green, yellow",
    eye_color: "yellow",
    birth_year: "NA",
    gender: "female",
    homeworld: "Zolan",
    species: "Clawdite"
  },
  {
    c_name: "Dexter Jettster",
    height: "198",
    mass: "102",
    hair_color: "none",
    skin_color: "brown",
    eye_color: "yellow",
    birth_year: "NA",
    gender: "male",
    homeworld: "Ojom",
    species: "Besalisk"
  },
  {
    c_name: "Lama Su",
    height: "229",
    mass: "88",
    hair_color: "none",
    skin_color: "grey",
    eye_color: "black",
    birth_year: "NA",
    gender: "male",
    homeworld: "Kamino",
    species: "Kaminoan"
  },
  {
    c_name: "Taun We",
    height: "213",
    mass: "",
    hair_color: "none",
    skin_color: "grey",
    eye_color: "black",
    birth_year: "NA",
    gender: "female",
    homeworld: "Kamino",
    species: "Kaminoan"
  },
  {
    c_name: "Jocasta Nu",
    height: "167",
    mass: "",
    hair_color: "white",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "NA",
    gender: "female",
    homeworld: "Coruscant",
    species: "Human"
  },
  {
    c_name: "Ratts Tyerell",
    height: "79",
    mass: "15",
    hair_color: "none",
    skin_color: "grey, blue",
    eye_color: "NA",
    birth_year: "NA",
    gender: "male",
    homeworld: "Aleen Minor",
    species: "Aleena"
  },
  {
    c_name: "R4-P17",
    height: "96",
    mass: "",
    hair_color: "none",
    skin_color: "silver, red",
    eye_color: "red, blue",
    birth_year: "NA",
    gender: "female",
    homeworld: "NA",
    species: "NA"
  },
  {
    c_name: "Wat Tambor",
    height: "193",
    mass: "48",
    hair_color: "none",
    skin_color: "green, grey",
    eye_color: "NA",
    birth_year: "NA",
    gender: "male",
    homeworld: "Skako",
    species: "Skakoan"
  },
  {
    c_name: "San Hill",
    height: "191",
    mass: "",
    hair_color: "none",
    skin_color: "grey",
    eye_color: "gold",
    birth_year: "NA",
    gender: "male",
    homeworld: "Muunilinst",
    species: "Muun"
  },
  {
    c_name: "Shaak Ti",
    height: "178",
    mass: "57",
    hair_color: "none",
    skin_color: "red, blue, white",
    eye_color: "black",
    birth_year: "NA",
    gender: "female",
    homeworld: "Shili",
    species: "Togruta"
  },
  {
    c_name: "Grievous",
    height: "216",
    mass: "159",
    hair_color: "none",
    skin_color: "brown, white",
    eye_color: "green, yellow",
    birth_year: "NA",
    gender: "male",
    homeworld: "Kalee",
    species: "Kaleesh"
  },
  {
    c_name: "Tarfful",
    height: "234",
    mass: "136",
    hair_color: "brown",
    skin_color: "brown",
    eye_color: "blue",
    birth_year: "NA",
    gender: "male",
    homeworld: "Kashyyyk",
    species: "Wookiee"
  },
  {
    c_name: "Raymus Antilles",
    height: "188",
    mass: "79",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "NA",
    gender: "male",
    homeworld: "Alderaan",
    species: "Human"
  },
  {
    c_name: "Sly Moore",
    height: "178",
    mass: "48",
    hair_color: "none",
    skin_color: "pale",
    eye_color: "white",
    birth_year: "NA",
    gender: "female",
    homeworld: "Umbara",
    species: "NA"
  },
  {
    c_name: "Tion Medon",
    height: "206",
    mass: "80",
    hair_color: "none",
    skin_color: "grey",
    eye_color: "black",
    birth_year: "NA",
    gender: "male",
    homeworld: "Utapau",
    species: "Pau'an"
  },
  {
    c_name: "Finn",
    height: "",
    mass: "",
    hair_color: "black",
    skin_color: "dark",
    eye_color: "dark",
    birth_year: "NA",
    gender: "male",
    homeworld: "NA",
    species: "Human"
  },
  {
    c_name: "Rey",
    height: "",
    mass: "",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "hazel",
    birth_year: "NA",
    gender: "female",
    homeworld: "NA",
    species: "Human"
  },
  {
    c_name: "Poe Dameron",
    height: "",
    mass: "",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "NA",
    gender: "male",
    homeworld: "NA",
    species: "Human"
  },
  {
    c_name: "BB8",
    height: "",
    mass: "",
    hair_color: "none",
    skin_color: "none",
    eye_color: "black",
    birth_year: "NA",
    gender: "none",
    homeworld: "NA",
    species: "Droid"
  },
  {
    c_name: "Captain Phasma",
    height: "",
    mass: "",
    hair_color: "NA",
    skin_color: "NA",
    eye_color: "NA",
    birth_year: "NA",
    gender: "female",
    homeworld: "NA",
    species: "NA"
  },
  {
    c_name: "Padmé Amidala",
    height: "165",
    mass: "45",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "46BBY",
    gender: "female",
    homeworld: "Naboo",
    species: "Human"
  },
  {
    c_name: ""
  }
]