 species = [
  {
    s_name: "Hutt",
    classification: "gastropod",
    designation: "sentient",
    average_height: "300",
    skin_colors: "green, brown, tan",
    hair_colors: "NA",
    eye_colors: "yellow, red",
    average_lifespan: "1000",
    s_language: "Huttese",
    homeworld: "Nal Hutta"
  },
  {
    s_name: "Yoda's species",
    classification: "mammal",
    designation: "sentient",
    average_height: "66",
    skin_colors: "green, yellow",
    hair_colors: "brown, white",
    eye_colors: "brown, green, yellow",
    average_lifespan: "900",
    s_language: "Galactic basic",
    homeworld: "NA"
  },
  {
    s_name: "Trandoshan",
    classification: "reptile",
    designation: "sentient",
    average_height: "200",
    skin_colors: "brown, green",
    hair_colors: "none",
    eye_colors: "yellow, orange",
    average_lifespan: "",
    s_language: "Dosh",
    homeworld: "Trandosha"
  },
  {
    s_name: "Mon Calamari",
    classification: "amphibian",
    designation: "sentient",
    average_height: "160",
    skin_colors: "red, blue, brown, magenta",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "",
    s_language: "Mon Calamarian",
    homeworld: "Mon Cala"
  },
  {
    s_name: "Ewok",
    classification: "mammal",
    designation: "sentient",
    average_height: "100",
    skin_colors: "brown",
    hair_colors: "white, brown, black",
    eye_colors: "orange, brown",
    average_lifespan: "",
    s_language: "Ewokese",
    homeworld: "Endor"
  },
  {
    s_name: "Sullustan",
    classification: "mammal",
    designation: "sentient",
    average_height: "180",
    skin_colors: "pale",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "",
    s_language: "Sullutese",
    homeworld: "Sullust"
  },
  {
    s_name: "Neimodian",
    classification: "NA",
    designation: "sentient",
    average_height: "180",
    skin_colors: "grey, green",
    hair_colors: "none",
    eye_colors: "red, pink",
    average_lifespan: "",
    s_language: "Neimoidia",
    homeworld: "Cato Neimoidia"
  },
  {
    s_name: "Gungan",
    classification: "amphibian",
    designation: "sentient",
    average_height: "190",
    skin_colors: "brown, green",
    hair_colors: "none",
    eye_colors: "orange",
    average_lifespan: "",
    s_language: "Gungan basic",
    homeworld: "Naboo"
  },
  {
    s_name: "Toydarian",
    classification: "mammal",
    designation: "sentient",
    average_height: "120",
    skin_colors: "blue, green, grey",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "91",
    s_language: "Toydarian",
    homeworld: "Toydaria"
  },
  {
    s_name: "Dug",
    classification: "mammal",
    designation: "sentient",
    average_height: "100",
    skin_colors: "brown, purple, grey, red",
    hair_colors: "none",
    eye_colors: "yellow, blue",
    average_lifespan: "",
    s_language: "Dugese",
    homeworld: "Malastare"
  },
  {
    s_name: "Twi'lek",
    classification: "mammals",
    designation: "sentient",
    average_height: "200",
    skin_colors: "orange, yellow, blue, green, pink, purple, tan",
    hair_colors: "none",
    eye_colors: "blue, brown, orange, pink",
    average_lifespan: "",
    s_language: "Twi'leki",
    homeworld: "Ryloth"
  },
  {
    s_name: "Aleena",
    classification: "reptile",
    designation: "sentient",
    average_height: "80",
    skin_colors: "blue, gray",
    hair_colors: "none",
    eye_colors: "NA",
    average_lifespan: "79",
    s_language: "Aleena",
    homeworld: "Aleen Minor"
  },
  {
    s_name: "Vulptereen",
    classification: "NA",
    designation: "sentient",
    average_height: "100",
    skin_colors: "grey",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "",
    s_language: "vulpterish",
    homeworld: "Vulpter"
  },
  {
    s_name: "Xexto",
    classification: "NA",
    designation: "sentient",
    average_height: "125",
    skin_colors: "grey, yellow, purple",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "",
    s_language: "Xextese",
    homeworld: "Troiken"
  },
  {
    s_name: "Toong",
    classification: "NA",
    designation: "sentient",
    average_height: "200",
    skin_colors: "grey, green, yellow",
    hair_colors: "none",
    eye_colors: "orange",
    average_lifespan: "",
    s_language: "Tundan",
    homeworld: "Tund"
  },
  {
    s_name: "Cerean",
    classification: "mammal",
    designation: "sentient",
    average_height: "200",
    skin_colors: "pale pink",
    hair_colors: "red, blond, black, white",
    eye_colors: "hazel",
    average_lifespan: "",
    s_language: "Cerean",
    homeworld: "Cerea"
  },
  {
    s_name: "Nautolan",
    classification: "amphibian",
    designation: "sentient",
    average_height: "180",
    skin_colors: "green, blue, brown, red",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "70",
    s_language: "Nautila",
    homeworld: "Glee Anselm"
  },
  {
    s_name: "Zabrak",
    classification: "mammal",
    designation: "sentient",
    average_height: "180",
    skin_colors: "pale, brown, red, orange, yellow",
    hair_colors: "black",
    eye_colors: "brown, orange",
    average_lifespan: "",
    s_language: "Zabraki",
    homeworld: "Iridonia"
  },
  {
    s_name: "Tholothian",
    classification: "mammal",
    designation: "sentient",
    average_height: "",
    skin_colors: "dark",
    hair_colors: "NA",
    eye_colors: "blue, indigo",
    average_lifespan: "",
    s_language: "NA",
    homeworld: "Tholoth"
  },
  {
    s_name: "Iktotchi",
    classification: "NA",
    designation: "sentient",
    average_height: "180",
    skin_colors: "pink",
    hair_colors: "none",
    eye_colors: "orange",
    average_lifespan: "",
    s_language: "Iktotchese",
    homeworld: "Iktotch"
  },
  {
    s_name: "Quermian",
    classification: "mammal",
    designation: "sentient",
    average_height: "240",
    skin_colors: "white",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "86",
    s_language: "Quermian",
    homeworld: "Quermia"
  },
  {
    s_name: "Kel Dor",
    classification: "NA",
    designation: "sentient",
    average_height: "180",
    skin_colors: "peach, orange, red",
    hair_colors: "none",
    eye_colors: "black, silver",
    average_lifespan: "70",
    s_language: "Kel Dor",
    homeworld: "Dorin"
  },
  {
    s_name: "Chagrian",
    classification: "amphibian",
    designation: "sentient",
    average_height: "190",
    skin_colors: "blue",
    hair_colors: "none",
    eye_colors: "blue",
    average_lifespan: "",
    s_language: "Chagria",
    homeworld: "Champala"
  },
  {
    s_name: "Geonosian",
    classification: "insectoid",
    designation: "sentient",
    average_height: "178",
    skin_colors: "green, brown",
    hair_colors: "none",
    eye_colors: "green, hazel",
    average_lifespan: "",
    s_language: "Geonosian",
    homeworld: "Geonosis"
  },
  {
    s_name: "Mirialan",
    classification: "mammal",
    designation: "sentient",
    average_height: "180",
    skin_colors: "yellow, green",
    hair_colors: "black, brown",
    eye_colors: "blue, green, red, yellow, brown, orange",
    average_lifespan: "",
    s_language: "Mirialan",
    homeworld: "Mirial"
  },
  {
    s_name: "Clawdite",
    classification: "reptilian",
    designation: "sentient",
    average_height: "180",
    skin_colors: "green, yellow",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "70",
    s_language: "Clawdite",
    homeworld: "Zolan"
  },
  {
    s_name: "Besalisk",
    classification: "amphibian",
    designation: "sentient",
    average_height: "178",
    skin_colors: "brown",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "75",
    s_language: "besalisk",
    homeworld: "Ojom"
  },
  {
    s_name: "Kaminoan",
    classification: "amphibian",
    designation: "sentient",
    average_height: "220",
    skin_colors: "grey, blue",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "80",
    s_language: "Kaminoan",
    homeworld: "Kamino"
  },
  {
    s_name: "Skakoan",
    classification: "mammal",
    designation: "sentient",
    average_height: "",
    skin_colors: "grey, green",
    hair_colors: "none",
    eye_colors: "NA",
    average_lifespan: "",
    s_language: "Skakoan",
    homeworld: "Skako"
  },
  {
    s_name: "Muun",
    classification: "mammal",
    designation: "sentient",
    average_height: "190",
    skin_colors: "grey, white",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "100",
    s_language: "Muun",
    homeworld: "Muunilinst"
  },
  {
    s_name: "Togruta",
    classification: "mammal",
    designation: "sentient",
    average_height: "180",
    skin_colors: "red, white, orange, yellow, green, blue",
    hair_colors: "none",
    eye_colors: "red, orange, yellow, green, blue, black",
    average_lifespan: "94",
    s_language: "Togruti",
    homeworld: "Shili"
  },
  {
    s_name: "Kaleesh",
    classification: "reptile",
    designation: "sentient",
    average_height: "170",
    skin_colors: "brown, orange, tan",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "80",
    s_language: "Kaleesh",
    homeworld: "Kalee"
  },
  {
    s_name: "Pau'an",
    classification: "mammal",
    designation: "sentient",
    average_height: "190",
    skin_colors: "grey",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "700",
    s_language: "Utapese",
    homeworld: "Utapau"
  },
  {
    s_name: "Wookiee",
    classification: "mammal",
    designation: "sentient",
    average_height: "210",
    skin_colors: "gray",
    hair_colors: "black, brown",
    eye_colors: "blue, green, yellow, brown, golden, red",
    average_lifespan: "400",
    s_language: "Shyriiwook",
    homeworld: "Kashyyyk"
  },
  {
    s_name: "Droid",
    classification: "artificial",
    designation: "sentient",
    average_height: "",
    skin_colors: "NA",
    hair_colors: "NA",
    eye_colors: "NA",
    average_lifespan: "",
    s_language: "NA",
    homeworld: "NA"
  },
  {
    s_name: "Human",
    classification: "mammal",
    designation: "sentient",
    average_height: "180",
    skin_colors: "caucasian, black, asian, hispanic",
    hair_colors: "blonde, brown, black, red",
    eye_colors: "brown, blue, green, hazel, grey, amber",
    average_lifespan: "120",
    s_language: "Galactic Basic",
    homeworld: "Coruscant"
  },
  {
    s_name: "Rodian",
    classification: "sentient",
    designation: "reptilian",
    average_height: "170",
    skin_colors: "green, blue",
    hair_colors: "NA",
    eye_colors: "black",
    average_lifespan: "",
    s_language: "Galactic Basic",
    homeworld: "Rodia"
  },
  {
    s_name: ""
  }
]