vehicle = [
  {
    v_name: "Sand Crawler",
    model: "Digger Crawler",
    manufacturer: "Corellia Mining Corporation",
    cost_in_credits: "150000",
    v_length: "36.8",
    max_atmosphering_speed: "30",
    crew: "46",
    passengers: "30",
    cargo_capacity: "50000",
    consumables: "2 months",
    vehicle_class: "wheeled"
  },
  {
    v_name: "T-16 skyhopper",
    model: "T-16 skyhopper",
    manufacturer: "Incom Corporation",
    cost_in_credits: "14500",
    v_length: "10.4",
    max_atmosphering_speed: "1200",
    crew: "1",
    passengers: "1",
    cargo_capacity: "50",
    consumables: "0",
    vehicle_class: "repulsorcraft"
  },
  {
    v_name: "X-34 landspeeder",
    model: "X-34 landspeeder",
    manufacturer: "SoroSuub Corporation",
    cost_in_credits: "10550",
    v_length: "3.4",
    max_atmosphering_speed: "250",
    crew: "1",
    passengers: "1",
    cargo_capacity: "5",
    consumables: "NA",
    vehicle_class: "repulsorcraft"
  },
  {
    v_name: "TIE/LN starfighter",
    model: "Twin Ion Engine/Ln Starfighter",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "",
    v_length: "6.4",
    max_atmosphering_speed: "1200",
    crew: "1",
    passengers: "0",
    cargo_capacity: "65",
    consumables: "2 days",
    vehicle_class: "starfighter"
  },
  {
    v_name: "Snowspeeder",
    model: "t-47 airspeeder",
    manufacturer: "Incom corporation",
    cost_in_credits: "",
    v_length: "4.5",
    max_atmosphering_speed: "650",
    crew: "2",
    passengers: "0",
    cargo_capacity: "10",
    consumables: "none",
    vehicle_class: "airspeeder"
  },
  {
    v_name: "TIE bomber",
    model: "TIE/sa bomber",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "",
    v_length: "7.8",
    max_atmosphering_speed: "850",
    crew: "1",
    passengers: "0",
    cargo_capacity: "",
    consumables: "2 days",
    vehicle_class: "space/planetary bomber"
  },
  {
    v_name: "AT-AT",
    model: "All Terrain Armored Transport",
    manufacturer: "Kuat Drive Yards, Imperial Department of Military Research",
    cost_in_credits: "",
    v_length: "20",
    max_atmosphering_speed: "60",
    crew: "5",
    passengers: "40",
    cargo_capacity: "1000",
    consumables: "NA",
    vehicle_class: "assault walker"
  },
  {
    v_name: "AT-ST",
    model: "All Terrain Scout Transport",
    manufacturer: "Kuat Drive Yards, Imperial Department of Military Research",
    cost_in_credits: "",
    v_length: "2",
    max_atmosphering_speed: "90",
    crew: "2",
    passengers: "0",
    cargo_capacity: "200",
    consumables: "none",
    vehicle_class: "walker"
  },
  {
    v_name: "Storm IV Twin-Pod cloud car",
    model: "Storm IV Twin-Pod",
    manufacturer: "Bespin Motors",
    cost_in_credits: "75000",
    v_length: "7",
    max_atmosphering_speed: "1500",
    crew: "2",
    passengers: "0",
    cargo_capacity: "10",
    consumables: "1 day",
    vehicle_class: "repulsorcraft"
  },
  {
    v_name: "Sail barge",
    model: "Modified Luxury Sail Barge",
    manufacturer: "Ubrikkian Industries Custom Vehicle Division",
    cost_in_credits: "285000",
    v_length: "30",
    max_atmosphering_speed: "100",
    crew: "26",
    passengers: "500",
    cargo_capacity: "2000000",
    consumables: "Live food tanks",
    vehicle_class: "sail barge"
  },
  {
    v_name: "Bantha-II cargo skiff",
    model: "Bantha-II",
    manufacturer: "Ubrikkian Industries",
    cost_in_credits: "8000",
    v_length: "9.5",
    max_atmosphering_speed: "250",
    crew: "5",
    passengers: "16",
    cargo_capacity: "135000",
    consumables: "1 day",
    vehicle_class: "repulsorcraft cargo skiff"
  },
  {
    v_name: "TIE/IN interceptor",
    model: "Twin Ion Engine Interceptor",
    manufacturer: "Sienar Fleet Systems",
    cost_in_credits: "",
    v_length: "9.6",
    max_atmosphering_speed: "1250",
    crew: "1",
    passengers: "0",
    cargo_capacity: "75",
    consumables: "2 days",
    vehicle_class: "starfighter"
  },
  {
    v_name: "Imperial Speeder Bike",
    model: "74-Z speeder bike",
    manufacturer: "Aratech Repulsor Company",
    cost_in_credits: "8000",
    v_length: "3",
    max_atmosphering_speed: "360",
    crew: "1",
    passengers: "1",
    cargo_capacity: "4",
    consumables: "1 day",
    vehicle_class: "speeder"
  },
  {
    v_name: "Vulture Droid",
    model: "Vulture-class droid starfighter",
    manufacturer: "Haor Chall Engineering, Baktoid Armor Workshop",
    cost_in_credits: "",
    v_length: "3.5",
    max_atmosphering_speed: "1200",
    crew: "0",
    passengers: "0",
    cargo_capacity: "0",
    consumables: "none",
    vehicle_class: "starfighter"
  },
  {
    v_name: "Multi-Troop Transport",
    model: "Multi-Troop Transport",
    manufacturer: "Baktoid Armor Workshop",
    cost_in_credits: "138000",
    v_length: "31",
    max_atmosphering_speed: "35",
    crew: "4",
    passengers: "112",
    cargo_capacity: "12000",
    consumables: "NA",
    vehicle_class: "repulsorcraft"
  },
  {
    v_name: "Armored Assault Tank",
    model: "Armoured Assault Tank",
    manufacturer: "Baktoid Armor Workshop",
    cost_in_credits: "",
    v_length: "9.75",
    max_atmosphering_speed: "55",
    crew: "4",
    passengers: "6",
    cargo_capacity: "",
    consumables: "NA",
    vehicle_class: "repulsorcraft"
  },
  {
    v_name: "Single Trooper Aerial Platform",
    model: "Single Trooper Aerial Platform",
    manufacturer: "Baktoid Armor Workshop",
    cost_in_credits: "2500",
    v_length: "2",
    max_atmosphering_speed: "400",
    crew: "1",
    passengers: "0",
    cargo_capacity: "",
    consumables: "none",
    vehicle_class: "repulsorcraft"
  },
  {
    v_name: "C-9979 landing craft",
    model: "C-9979 landing craft",
    manufacturer: "Haor Chall Engineering",
    cost_in_credits: "200000",
    v_length: "210",
    max_atmosphering_speed: "587",
    crew: "140",
    passengers: "284",
    cargo_capacity: "1800000",
    consumables: "1 day",
    vehicle_class: "landing craft"
  },
  {
    v_name: "Tribubble bongo",
    model: "Tribubble bongo",
    manufacturer: "Otoh Gunga Bongameken Cooperative",
    cost_in_credits: "",
    v_length: "15",
    max_atmosphering_speed: "85",
    crew: "1",
    passengers: "2",
    cargo_capacity: "1600",
    consumables: "NA",
    vehicle_class: "submarine"
  },
  {
    v_name: "Sith speeder",
    model: "FC-20 speeder bike",
    manufacturer: "Razalon",
    cost_in_credits: "4000",
    v_length: "1.5",
    max_atmosphering_speed: "180",
    crew: "1",
    passengers: "0",
    cargo_capacity: "2",
    consumables: "NA",
    vehicle_class: "speeder"
  },
  {
    v_name: "Zephyr-G swoop bike",
    model: "Zephyr-G swoop bike",
    manufacturer: "Mobquet Swoops and Speeders",
    cost_in_credits: "5750",
    v_length: "3.68",
    max_atmosphering_speed: "350",
    crew: "1",
    passengers: "1",
    cargo_capacity: "200",
    consumables: "none",
    vehicle_class: "repulsorcraft"
  },
  {
    v_name: "Koro-2 Exodrive airspeeder",
    model: "Koro-2 Exodrive airspeeder",
    manufacturer: "Desler Gizh Outworld Mobility Corporation",
    cost_in_credits: "",
    v_length: "6.6",
    max_atmosphering_speed: "800",
    crew: "1",
    passengers: "1",
    cargo_capacity: "80",
    consumables: "NA",
    vehicle_class: "airspeeder"
  },
  {
    v_name: "XJ-6 airspeeder",
    model: "XJ-6 airspeeder",
    manufacturer: "Narglatch AirTech prefabricated kit",
    cost_in_credits: "",
    v_length: "6.23",
    max_atmosphering_speed: "720",
    crew: "1",
    passengers: "1",
    cargo_capacity: "",
    consumables: "NA",
    vehicle_class: "airspeeder"
  },
  {
    v_name: "LAAT/i",
    model: "Low Altitude Assault Transport/infrantry",
    manufacturer: "Rothana Heavy Engineering",
    cost_in_credits: "",
    v_length: "17.4",
    max_atmosphering_speed: "620",
    crew: "6",
    passengers: "30",
    cargo_capacity: "170",
    consumables: "NA",
    vehicle_class: "gunship"
  },
  {
    v_name: "LAAT/c",
    model: "Low Altitude Assault Transport/carrier",
    manufacturer: "Rothana Heavy Engineering",
    cost_in_credits: "",
    v_length: "28.82",
    max_atmosphering_speed: "620",
    crew: "1",
    passengers: "0",
    cargo_capacity: "40000",
    consumables: "NA",
    vehicle_class: "gunship"
  },
  {
    v_name: "Tsmeu-6 personal wheel bike",
    model: "Tsmeu-6 personal wheel bike",
    manufacturer: "Z-Gomot Ternbuell Guppat Corporation",
    cost_in_credits: "15000",
    v_length: "3.5",
    max_atmosphering_speed: "330",
    crew: "1",
    passengers: "1",
    cargo_capacity: "10",
    consumables: "none",
    vehicle_class: "wheeled walker"
  },
  {
    v_name: "Emergency Firespeeder",
    model: "Fire suppression speeder",
    manufacturer: "NA",
    cost_in_credits: "",
    v_length: "",
    max_atmosphering_speed: "",
    crew: "2",
    passengers: "",
    cargo_capacity: "",
    consumables: "NA",
    vehicle_class: "fire suppression ship"
  },
  {
    v_name: "Droid tri-fighter",
    model: "tri-fighter",
    manufacturer: "Colla Designs, Phlac-Arphocc Automata Industries",
    cost_in_credits: "20000",
    v_length: "5.4",
    max_atmosphering_speed: "1180",
    crew: "1",
    passengers: "0",
    cargo_capacity: "0",
    consumables: "none",
    vehicle_class: "droid starfighter"
  },
  {
    v_name: "Oevvaor jet catamaran",
    model: "Oevvaor jet catamaran",
    manufacturer: "Appazanna Engineering Works",
    cost_in_credits: "12125",
    v_length: "15.1",
    max_atmosphering_speed: "420",
    crew: "2",
    passengers: "2",
    cargo_capacity: "50",
    consumables: "3 days",
    vehicle_class: "airspeeder"
  },
  {
    v_name: "Raddaugh Gnasp fluttercraft",
    model: "Raddaugh Gnasp fluttercraft",
    manufacturer: "Appazanna Engineering Works",
    cost_in_credits: "14750",
    v_length: "7",
    max_atmosphering_speed: "310",
    crew: "2",
    passengers: "0",
    cargo_capacity: "20",
    consumables: "none",
    vehicle_class: "air speeder"
  },
  {
    v_name: "Clone turbo tank",
    model: "HAVw A6 Juggernaut",
    manufacturer: "Kuat Drive Yards",
    cost_in_credits: "350000",
    v_length: "49.4",
    max_atmosphering_speed: "160",
    crew: "20",
    passengers: "300",
    cargo_capacity: "30000",
    consumables: "20 days",
    vehicle_class: "wheeled walker"
  },
  {
    v_name: "Corporate Alliance tank droid",
    model: "NR-N99 Persuader-class droid enforcer",
    manufacturer: "Techno Union",
    cost_in_credits: "49000",
    v_length: "10.96",
    max_atmosphering_speed: "100",
    crew: "0",
    passengers: "4",
    cargo_capacity: "",
    consumables: "none",
    vehicle_class: "droid tank"
  },
  {
    v_name: "Droid gunship",
    model: "HMP droid gunship",
    manufacturer: "Baktoid Fleet Ordnance, Haor Chall Engineering",
    cost_in_credits: "60000",
    v_length: "12.3",
    max_atmosphering_speed: "820",
    crew: "0",
    passengers: "0",
    cargo_capacity: "0",
    consumables: "none",
    vehicle_class: "airspeeder"
  },
  {
    v_name: "AT-RT",
    model: "All Terrain Recon Transport",
    manufacturer: "Kuat Drive Yards",
    cost_in_credits: "40000",
    v_length: "3.2",
    max_atmosphering_speed: "90",
    crew: "1",
    passengers: "0",
    cargo_capacity: "20",
    consumables: "1 day",
    vehicle_class: "walker"
  },
  {
    v_name: "AT-TE",
    model: "All Terrain Tactical Enforcer",
    manufacturer: "Rothana Heavy Engineering, Kuat Drive Yards",
    cost_in_credits: "",
    v_length: "13.2",
    max_atmosphering_speed: "60",
    crew: "6",
    passengers: "36",
    cargo_capacity: "10000",
    consumables: "21 days",
    vehicle_class: "walker"
  },
  {
    v_name: "SPHA",
    model: "Self-Propelled Heavy Artillery",
    manufacturer: "Rothana Heavy Engineering",
    cost_in_credits: "",
    v_length: "140",
    max_atmosphering_speed: "35",
    crew: "25",
    passengers: "30",
    cargo_capacity: "500",
    consumables: "7 days",
    vehicle_class: "walker"
  },
  {
    v_name: "Flitknot speeder",
    model: "Flitknot speeder",
    manufacturer: "Huppla Pasa Tisc Shipwrights Collective",
    cost_in_credits: "8000",
    v_length: "2",
    max_atmosphering_speed: "634",
    crew: "1",
    passengers: "0",
    cargo_capacity: "",
    consumables: "NA",
    vehicle_class: "speeder"
  },
  {
    v_name: "Neimoidian shuttle",
    model: "Sheathipede-class transport shuttle",
    manufacturer: "Haor Chall Engineering",
    cost_in_credits: "",
    v_length: "20",
    max_atmosphering_speed: "880",
    crew: "2",
    passengers: "6",
    cargo_capacity: "1000",
    consumables: "7 days",
    vehicle_class: "transport"
  },
  {
    v_name: "Geonosian starfighter",
    model: "Nantex-class territorial defense",
    manufacturer: "Huppla Pasa Tisc Shipwrights Collective",
    cost_in_credits: "",
    v_length: "9.8",
    max_atmosphering_speed: "20000",
    crew: "1",
    passengers: "0",
    cargo_capacity: "",
    consumables: "NA",
    vehicle_class: "starfighter"
  },
  {
    v_name: ""
  }
]